### ISSUE TITLE
scrolling jumps to top unexpectedly in Chrome

### ISSUE THREAD

**Issue by spiritfingerz** [WeCodePixels/theia-sticky-sidebar#11]
See for example http://cfm.us.mensa.org/open/admission-test-registration?test_session_id=1BU8Um3SkR. When in Chrome browser, this scrolls down and then when you get to the bottom jumps back up to the top.

**Comment by liviucmg** [comment]
Try changing the selector from ".leftSidebar, .content, .rightSidebar" to just ".leftSidebar".

**Comment by spiritfingerz** [comment]
If I could reach through the Interwebz and give you a high-five I would. That's awesome. I just removed the .content and it fixed it; I left the .rightSidebar in because I want to keep that sticky.

**Comment by liviucmg** [comment]
Woohoo! Thank you for the Internet high-five. :) If you would like to use .content as well, you would probably need to wrap it inside a `<div class="theiaStickySidebar">`. Have a great weekend!

**Comment by spiritfingerz** [comment]
Thanks so much! I always want the content to scroll and the sidebars to stick, so I'm 100% good to go! Woot! Have a great weekend. =)
