### ISSUE TITLE
detached sidebar on Android Tablet

### ISSUE THREAD

**Issue by m4w** [WeCodePixels/theia-sticky-sidebar#12]
We have an issue with our samsung test tablet and the theia sticky sidebar. If we zoom in and out quite fast, the sidebar will detach itself form the leftern site and then it flies around on the site. It happens even with you examples, so its not in our code. 
I will have a look into the theia code, but I would be very glad, if you can fix it. 

See image for further explaination:

![bildschirmfoto 2015-10-19 um 13 13 19](https://cloud.githubusercontent.com/assets/1598385/10576413/5f44bf86-7663-11e5-895e-a8e75b3fab47.png)

While on zoom the sidebar should stay on their original position. It should be fixed to top/bottom, but it shouldn't be left/right positioned.

**Comment by liviucmg** [comment]
I'm going to close this as it may have been solved in the meantime (lots of fixes since 2015), but feel free to open another issue if that isn't the case.
