### ISSUE TITLE
Does not work on iPad ios9 

### ISSUE THREAD

**Issue by Isodie** [WeCodePixels/theia-sticky-sidebar#15]
The plugin shows slow response behavior in safari iPad ios9

**Comment by arun-maddheshia** [comment]
please fix it soon it calculate height very slow in macbook safari

**Comment by liviucmg** [comment]
At the moment I do not have time to take on this issue, but a possible work-around might be to disable inertial scrolling on iOS: http://stackoverflow.com/a/33311860/148388 . Pull requests are of course welcomed.

**Comment by liviucmg** [comment]
Duplicate of #28
