### ISSUE TITLE
[Remove] console log

### ISSUE THREAD

**Issue by KLVTZ** [WeCodePixels/theia-sticky-sidebar#18]
Problem
-----------
Seems to only exist to indicate that the init function has executed. I think this is unnecessary as a user can easily console log if they are trying to debug. 

https://github.com/WeCodePixels/theia-sticky-sidebar/blob/master/js/theia-sticky-sidebar.js#L80

Solution
------------
Remove console log. Is TST a shorthand for TEST?

**Comment by liviucmg** [comment]
Merged, thanks! :+1: That line was a leftover from who knows when. :)
