### ISSUE TITLE
How to disable it on resize?

### ISSUE THREAD

**Issue by adods** [WeCodePixels/theia-sticky-sidebar#20]
Is there any way to disable it? On responsive page when the screen resolution changed from wide to narrow screen the sidebar always moved to the bottom, so the sticky needs to be disabled.

**Comment by liviucmg** [comment]
You can use the [`minWidth` option](https://github.com/WeCodePixels/theia-sticky-sidebar#minwidth) for that. For example if you're content is responsive at 900px, you set `minWidth` to 901; any screen width below that will disable the sidebar.
