### ISSUE TITLE
bower install theia-sticky-sidebar does not install the updated version of the code

### ISSUE THREAD

**Issue by frensuren** [WeCodePixels/theia-sticky-sidebar#29]
While using the plugin via bower the code does not seem to be updated. There is still deprecated usage of `size()` method on containerSelector. The bower package seem to be loading the source from different git path.

**Comment by liviucmg** [comment]
I just pushed a new v1.4.1 tag, you should get the latest commit with it. Try a `bower update` and let me know if it works.

Cheers :beers:

**Comment by frensuren** [comment]
@liviucmg thanks for the quick fix, its working now.

Cheers 🍻
