### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by scotthovestadt** [WeCodePixels/theia-sticky-sidebar#32]
Hello,

First of all, great work.

I'd like to use this on a project built with NPM/webpack. Is it possible to publish on NPM in addition to bower?

Thanks!

**Comment by liviucmg** [comment]
Can you please double-check the latest commit and let me know if `package.json` looks good? A `npm install theia-sticky-sidebar` should do the trick now.

**Comment by scotthovestadt** [comment]
Looks good to me. Thanks!
