### ISSUE TITLE
Theia breaking Slick Slider

### ISSUE THREAD

**Issue by nearkingdom** [WeCodePixels/theia-sticky-sidebar#33]
When I call both Theia Stickly Sidebar and Slick Slider on document load Theia seems to break the Slick Slider.

Any ideas why?

Slick: http://kenwheeler.github.io/slick/

**Comment by liviucmg** [comment]
Is the Slick Slider inside the sticky sidebar? If so, be sure to use a surrounding`<div class="theiaStickySidebar">` as per the docs.

Also, double-check if any errors pop up in the Console.
