### ISSUE TITLE
Stick on a Widget?

### ISSUE THREAD

**Issue by oralunal** [WeCodePixels/theia-sticky-sidebar#35]
Is there a way to make stick sidebar on a specific widget?

**Comment by liviucmg** [comment]
At the moment no, you can only make an entire sidebar sticky, not just a widget.

**Comment by oralunal** [comment]
How tutsplus handle this? They're sidebar banner is sticky. Not the whole sidebar.

**Comment by liviucmg** [comment]
They're using something else?
