### ISSUE TITLE
Google DFP ads appear and quickly disappear from sticky sidebar

### ISSUE THREAD

**Issue by steelmaiden** [WeCodePixels/theia-sticky-sidebar#37]
I use a sticky sidebar on my website - https://geek.hr/znanost and i have DFP ads in it.

The problem is that the right top sidebar ad will load and then disappear quickly.

This happens randomly in all browsers, but almost always in Edge browser.

Does anyone know what the problem is and how to fix it?

Thanks

**Comment by liviucmg** [comment]
This is the same issue as #7. You need to make sure you have the inner containers with class="theiaStickySidebar" right inside your sidebar. More info: https://github.com/WeCodePixels/theia-sticky-sidebar#usage
