### ISSUE TITLE
Top part of sidebar goes under header

### ISSUE THREAD

**Issue by dbd5** [WeCodePixels/theia-sticky-sidebar#38]
Hello,

Thanks for the work you put into this plugin!

This works great except that a portion of the sidebar like 20% goes under the header and continues perhaps until it reaches the top. My header is about 360px so I set additionalMarginTop:360 but it didn't help, it appears that the plugin does nothing with this value?.

The whole idea of this is to keep useful items completely visible as the user scrolls up and down the right content. Please help, thanks.

**Here's a screenshot of the relevant sections of my code;**

![screen shot 2017-01-29 at 1 36 29 am](https://cloud.githubusercontent.com/assets/9496750/22400982/ef51d700-e5c3-11e6-9f4a-eba60bf16405.png)

**Comment by dbd5** [comment]
No no, totally my bad - your code is amazing!

**Comment by liviucmg** [comment]
Hi, happy to hear it worked out! :) 🍻
