### ISSUE TITLE
destroy sticky sidebar

### ISSUE THREAD

**Issue by Fanni-Portier** [WeCodePixels/theia-sticky-sidebar#48]
Hi!

I want the sticky sidebar only on a viewport size 900 and bigger. How can I remove all the theia things in the code when I resize the window after loading the sticky sidebar? It causes problems on smaller screens.  

I used this code:
`
$(document).ready(function() {
    		
		    var $window = $(window);
		    
		    function stickySidebar() {
				if ( $(window).width() >= 901 ) {
				    $(document).ready(function() {
						$('.sidebar')
							.theiaStickySidebar();
					});
			    }
		    }
		    
		    $(window).scroll(function() {
	           stickySidebar();
	        });
	        
	        $(window).resize(function() {
	           stickySidebar();
	        });

	        $(document).ready(function() {
	            stickySidebar();
	        });
	});
`

**Comment by liviucmg** [comment]
There is a `minWidth` option you can use. The only code you need is this:
```
$(document).ready(function() {
    $('.sidebar').theiaStickySidebar({
        minWidth: 900
    });
});
```

Otherwise there isn't a way to completely "unload" the sticky sidebar.

**Comment by Fanni-Portier** [comment]
Oh boy!!! That easy!
Thanks :)
