### ISSUE TITLE
Transform: none - Added to a lot of elements

### ISSUE THREAD

**Issue by amichel86** [WeCodePixels/theia-sticky-sidebar#50]
Hi and thank you for your plugin!

However I am having an issue where "transform: none" is applied to a parent of a higher level and I don't understand why exactly. Here's a screenshot of what I am trying to describe. I am using an off-canvas nav and because of that the transition cannot occur. Is there a quick fix for this?

![image](https://user-images.githubusercontent.com/5871701/34003807-4145a928-e0c4-11e7-8a81-669ced97c4ca.png)

Thanks :)

**Comment by liviucmg** [comment]
Hi,

This is necessary because most transform rules cause the plugin to fail. But you are right, at the very least we should add an option to disable our 'transform: none' rules.

Cheers,
Liviu

**Comment by amichel86** [comment]
Hi @liviucmg  thanks for replying. However since I wrote you almost a year ago, I fixed the issue! :D
