### ISSUE TITLE
No documentation for disableOnResponsiveLayouts which is enabled by default

### ISSUE THREAD

**Issue by acjbizar** [WeCodePixels/theia-sticky-sidebar#51]
Sticky was working on some mobile devices, but not on others. By trial and error I found out this had to do with the width of the viewport. After trying a ton of different configurations (none of which helped one bit), I decided to read the source code, and that is where I found this option called `disableOnResponsiveLayouts`. Setting it to `false` when initializing did the trick. You might want to document this.

**Comment by liviucmg** [comment]
I'll document the option today, thanks for the suggestion and sorry I didn't add it sooner. :beers:

**Comment by acjbizar** [comment]
Thanks! Cheers!
