### ISSUE TITLE
All widgets are deleted when "Pre-render the inner container for each sidebar" activate

### ISSUE THREAD

**Issue by TobiasCintrao** [WeCodePixels/theia-sticky-sidebar#53]
All widgets are deleted (really deleted on the database) when we do some change on widget area.
The problem is related with "Pre-render the inner container for each sidebar", when this option are activated the plugin adds a div around the sidebars (even on admin area), and this cause the problem when adding/remove widgets if you refresh after, all widgets are gone, the drag and drop also stop working.

Add  "&& ! is_admin() " in the if in "dynamic_sidebar_before" and "dynamic_sidebar_after" solves the problem.

**Comment by liviucmg** [comment]
This has already been fixed in version 1.7.0 which you can download from CodeCanyon. Note that this is the repository for the JavaScript-only version, not the WordPress version.
