### ISSUE TITLE
Causes a javascript error in Gillian wordpress theme

### ISSUE THREAD

**Issue by gumusdesigngroup** [WeCodePixels/theia-sticky-sidebar#55]
scripts.js?ver=1.0:1062 Uncaught TypeError: $(...).theiaStickySidebar is not a function
    at HTMLDocument.<anonymous> (scripts.js?ver=1.0:1062)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

----

   $('#sidebar').theiaStickySidebar({
      additionalMarginTop: parseInt( $('.sh-header').height() + $('#wpadminbar').height() + 15 ),
      minWidth: 1026
    });

**Comment by liviucmg** [comment]
This is very specific and probably not a bug in our library. Perhaps you are using a caching plugin that's wrongly reordering the JS files. Either way, please [contacts us here for issues with the WordPress plugin](https://wecodepixels.com/submit-a-support-request/), or the theme's author if the plugin came bundled.
