### ISSUE TITLE
Sidebar doesn't stop for scrooling down

### ISSUE THREAD

**Issue by inegolmobilyan** [WeCodePixels/theia-sticky-sidebar#58]
hi guys I have a problem with sticky sidebar. The problem is the sticky sidebar doesn't stop. It is scrooling down forever and pushing the footer down.

[https://www.inegolmobilyan.com/musteri-hizmetleri](https://www.inegolmobilyan.com/musteri-hizmetleri)

**Comment by geosenna** [comment]
+1

**Comment by gheorghemitrescu88** [comment]
You can try this parameter set to false - updateSidebarHeight: false

**Comment by maulayyacyber** [comment]
hai @gheorghemitrescu88 when i'm use updateSidebarHeight: false, between sidebar and footer clash

**Comment by maulayyacyber** [comment]
![screen shot 2018-10-23 at 21 53 38](https://user-images.githubusercontent.com/11194525/47369571-29775300-d70e-11e8-8f6c-3d9f3bf6de55.png)

when im used updateSidebarHeight: false, any idea ?

**Comment by StancuFlorin** [comment]
Did you solved this problem?

**Comment by StancuFlorin** [comment]
I fixed it by adding

`var footerBottom = jQuery('#footer').outerHeight();

    jQuery('#sidebar.sticky').theiaStickySidebar({
      // Settings
      additionalMarginTop: marginTop,
	  additionalMarginBottom: footerBottom,
	  updateSidebarHeight: false
    });
`

**Comment by StancuFlorin** [comment]
I fixed it by adding `containerSelector: '#content'`
