### ISSUE TITLE
[HELP] Sidebar passes under page's element

### ISSUE THREAD

**Issue by RomainSUSSEST** [WeCodePixels/theia-sticky-sidebar#64]
I use Theia sticky sidebar for one of my menus but here I have an item on my page that exceeds its container and the menu passes below it.
This item is in position : absolute. I tried to change parameters to see if i could change the end of the "sticky" step of the menu. 

So I want to make the sticky phase end before the menu passes below the item which exceeds.

**Comment by liviucmg** [comment]
You could try using the `additionalMarginTop` setting, maybe that helps. Otherwise it's hard to figure out what's going on without a clear example.
