### ISSUE TITLE
Page scrolls infinitely

### ISSUE THREAD

**Issue by romancieciuch** [WeCodePixels/theia-sticky-sidebar#65]
Hello there!

I have an issue, you can see it here:
https://e-kursy-walut.pl/ranking-walut/

User can't scroll to the footer - as the page gets higher and higher.

Interesting thing, the same div order (layout) here, doesn't break the page:
https://e-kursy-walut.pl/kurs-bitcoin/

Thanks!

**Comment by liviucmg** [comment]
Hi @romancieciuch, the issue is no longer present on that link so I'm going to close this. If you can provide a minimal example to reproduce it, I can then reopen the ticket and have a look.
